### ISSUE TITLE
Regarding the SCHEDULED keyword

### ISSUE THREAD

**Issue by mgmart** [xiaoxinghu/CocoaOrg#4]
Is it in your plans to regard the SCHEDULED keyword? At the moment it shows up in the paragraph section where if I understand the library correctly only plain text is expected.

```
    ▿ Paragraph(text: SCHEDULED: <2016-12-16 Fri .+1d>)
      ▿ lines : 1 element
        - 0 : "SCHEDULED: <2016-12-16 Fri .+1d>"
```

**Comment by xiaoxinghu** [comment]
Yes, it will be implemented soon. Stay tuned.

**Comment by xiaoxinghu** [comment]
@mgmart I just implemented `Planning` syntax. Please try it out. Open new issues if you find any issues. Closing this one.

**Comment by mgmart** [comment]
`Planning` looks good. Will take some time before I could work further with SwiftOrg.
